export const profile = {
  name: "Mercy Naliaka Moraa",
  shortName: "Mercy Moraa",
  role: "Software Engineer",
  location: "Kisumu, Kenya",
  locationNote: "Open to remote work and relocation",
  email: "mercymoraa012@gmail.com",
  phone: "+254 757 450 853",
  bio: "I build for performance, concurrency, and domain-grounded AI. My apprenticeship at Zone01 Kisumu has me deep in Go and concurrent pipelines, alongside real-world GraphRAG architectures at DigiCow AI and automated financial reconciliation at LedgerMate. I think in systems, memory safety, and outcomes people actually feel.",
  socials: {
    linkedin: "https://www.linkedin.com/in/mercy-moraa-00a780363/",
    github: "https://github.com/Moraa021",
    devto: "https://dev.to/memoraa",
    x: "https://x.com/memoraa012",
    email: "mailto:mercymoraa012@gmail.com",
  },
  resume: "/assets/Mercy_Naliaka_Moraa_Resume.pdf",
  awards: [
    "National Finalist, Kenya AI Challenge (Nairobi Finals)",
    "Medalist, KijaniSpace Climate-Smart Agritech Hackathon",
    "Creator of Nemo, an Earth observation agritech platform",
  ],
};

export const metrics = [
  { num: "2+", label: "Deployed systems in production" },
  { num: "38+", label: "Public repositories and modules" },
  { num: "Finalist", label: "Kenya AI Challenge, Nairobi" },
  { num: "14+", label: "REST APIs and automated webhooks" },
];

export const pillars = [
  {
    icon: "target",
    title: "Production-grade rigor",
    text: "Idempotent webhooks, zero double-counting, automated regression tests, and memory-safe concurrent pipelines.",
  },
  {
    icon: "link",
    title: "Domain-grounded AI",
    text: "Linking Neo4j knowledge graphs with GraphRAG to ground AI outputs in peer-reviewed scientific manuals.",
  },
];

export const quickFacts = [
  { label: "Location", value: "Kisumu, Kenya. Open to worldwide remote work and relocation." },
  { label: "Education", value: "BSc in ICT Management, Maseno University, Class of 2026" },
  { label: "Specialization", value: "Go concurrency, Python backends, GraphRAG and knowledge graphs" },
  { label: "Current focus", value: "Software Engineer Apprentice at Zone01 Kisumu" },
];

export const journey = [
  {
    id: "maseno-edu",
    step: 1,
    period: "2022 – Nov 2026",
    role: "BSc in ICT Management",
    company: "Maseno University",
    location: "Maseno, Kenya",
    badge: "Academic Grounding",
    summary:
      "Graduating with foundations in distributed systems, relational database architecture, algorithms, and applied machine learning.",
    skills: ["Distributed Systems", "Database Design", "Algorithms", "Applied ML"],
    coordinates: "0°00′17″S 34°36′01″E",
  },
  {
    id: "maseno-it",
    step: 2,
    period: "2024 – 2025",
    role: "Industrial Attachment",
    company: "Maseno IT Infrastructure",
    location: "Maseno, Kenya",
    badge: "Infrastructure & Networks",
    summary:
      "Administered campus network routing, maintained workstation uptime, and provided direct system troubleshooting for administrative departments.",
    skills: ["Network Routing", "Linux Workstations", "Hardware Uptime", "IT Support"],
    coordinates: "0°00′12″S 34°35′50″E",
  },
  {
    id: "jagedo-qa",
    step: 3,
    period: "Aug 2026",
    role: "QA Tester, Contract",
    company: "JaGedo",
    location: "Kisumu, Kenya",
    badge: "Quality & API Auditing",
    summary:
      "End-to-end manual and API QA testing for a live marketplace platform. Audited multi-role checkout flows, identified edge cases, and tracked defect lifecycles alongside engineering and product teams.",
    skills: ["API Testing", "Postman", "Defect Lifecycle", "Multi-role Checkout"],
    coordinates: "0°05′21″S 34°45′14″E",
  },
  {
    id: "zone01-apprentice",
    step: 4,
    period: "Jun 2026 – Present",
    role: "Software Engineer Apprentice",
    company: "Zone01 Kisumu",
    location: "Kisumu, Kenya",
    badge: "Go Concurrency & Systems",
    summary:
      "Immersive systems engineering apprenticeship centered on Go. Architecting concurrent worker pipelines, optimizing memory allocation, and solving algorithmic challenges in collaborative sprint reviews.",
    skills: ["Go", "Goroutines & Channels", "Worker Pools", "Memory Safety"],
    coordinates: "0°05′54″S 34°45′28″E",
    featured: true,
  },
];

export const projects = [
  {
    id: "digicow",
    category: "ai",
    type: "Team project",
    tags: ["Kenya AI Challenge National Finalist", "GraphRAG and LLM grounding", "Bilingual system"],
    title: "DigiCow AI, Farmer Intelligence System",
    subtitle: "AI-powered decision support for youth extension agents",
    description:
      "Smallholder farmers in Kenya need fast, accurate agritech advice without the risk of AI hallucinations. DigiCow AI bridges domain agricultural knowledge with retrieval-grounded AI to deliver verified field recommendations.",
    bullets: [
      { label: "Neo4j knowledge graph", text: "Modeled relational dependencies between smallholder profiles, soil parameters, livestock medical histories, and localized disease vectors." },
      { label: "Zero-hallucination GraphRAG", text: "Engineered a retrieval pipeline with Featherless AI grounded in official KALRO and ILRI manuals for verified field accuracy." },
      { label: "Bilingual diagnostics", text: "Built low-latency FastAPI endpoints serving localized advisories in English and Swahili with prioritized follow-up task queues." },
    ],
    tech: ["Python", "FastAPI", "Neo4j (Cypher)", "GraphRAG", "Featherless AI", "Render"],
    liveUrl: "https://digicow-ai-farmer-intelligence-ui.onrender.com/",
    repoUrl: "https://github.com/Moraa021/digicow-ai-farmer-intelligence",
    image: "/assets/digicow-actual.png",
    imageAlt: "DigiCow AI extension agent dashboard",
    featured: true,
  },
  {
    id: "ledgermate",
    category: "fintech",
    type: "Personal project",
    tags: ["FinTech SaaS", "Automated reconciliation", "Paystack and M-Pesa"],
    title: "LedgerMate, Financial Management Platform",
    subtitle: "Bookkeeping and automated M-Pesa reconciliation for Kenyan businesses",
    description:
      "Informal traders and SMEs in Kenya lose hours manually reconciling mobile-money payments with sales records. LedgerMate automates transaction capture, inventory costing, and financial reporting in one lightweight tool.",
    bullets: [
      { label: "Cryptographic webhooks", text: "Built a Paystack integration (STK Push and C2B webhooks) with signature verification and idempotent processing, eliminating manual reconciliation." },
      { label: "14 REST API endpoints", text: "Engineered full ledger management, weighted-average inventory costing, and automated balance sheet and profit and loss generation." },
      { label: "Explainable forecasting", text: "Integrated linear regression forecasting over monthly trends and containerized the application with Docker and Gunicorn." },
    ],
    tech: ["Python", "Flask", "PostgreSQL", "SQLAlchemy", "Docker", "Vercel"],
    liveUrl: "https://ledger-mate-ecru.vercel.app/",
    repoUrl: "https://github.com/Moraa021/LedgerMate",
    image: "/assets/ledgermate-actual.png",
    imageAlt: "LedgerMate cash flow dashboard",
  },
  {
    id: "go-systems",
    category: "systems",
    type: "Personal project",
    tags: ["Systems programming", "Zone01 systems suite"],
    title: "Go Concurrency and Algorithmic Engines",
    subtitle: "High-throughput utilities and custom memory structures",
    description:
      "A collection of first-principles Go backend utilities and concurrent processing pipelines, built during the Zone01 Kisumu apprenticeship without relying on external libraries.",
    bullets: [
      { label: "Concurrency", text: "Worker pools, channel multiplexing, and mutex synchronization built to guarantee thread safety." },
      { label: "Algorithms", text: "Solutions for matrix transformations, ASCII typography parsers, and custom terminal utilities." },
    ],
    tech: ["Go", "Goroutines", "Channels", "Data Structures", "Linux"],
    liveUrl: "https://github.com/Moraa021/pamojabuild1",
    liveLabel: "Explore PamojaBuild",
    repoUrl: "https://github.com/Moraa021",
    repoLabel: "More repositories",
    stat: { value: "100%", label: "Zero external runtime dependencies" },
  },
];

export const reel = {
  poster: "/assets/reel-video-poster.jpg",
  sources: ["/assets/reel-presentation.mp4"],
  title: "DigiCow AI, live presentation reel",
  subtitle: "National Finalist pitch at the Kenya AI Challenge, Nairobi Finals",
  bullets: [
    { icon: "target", label: "The problem", text: "Smallholder dairy farmers across Kenya face productivity and herd health losses from delayed veterinary guidance and inaccurate diagnostics." },
    { icon: "network", label: "The architecture", text: "Built on a Neo4j knowledge graph and GraphRAG pipeline, eliminating LLM hallucinations and grounding advisories in official veterinary manuals." },
    { icon: "device", label: "Bilingual reach", text: "Low-latency FastAPI services delivering SMS and web recommendations in English and Swahili." },
  ],
  companion: {
    image: "/assets/fireside-interview.jpg",
    eyebrow: "Interview and discussion",
    title: "AI and software engineering",
    text: "An interview about bridging applied AI with solid software engineering foundations, concurrency, and verifiable domain data.",
    topics: [
      { label: "AI and engineering foundations", text: "Grounding intelligent workflows in rigorous backend principles." },
      { label: "Go concurrency in practice", text: "Designing thread-safe pipelines with goroutines and worker pools." },
      { label: "Domain-grounded problem solving", text: "Eliminating AI hallucinations in agricultural advisory systems." },
    ],
  },
};

export const moments = [
  {
    id: "kenya-ai-challenge",
    category: ["awards"],
    image: "/assets/ai-kenya-win.png",
    badge: "National Finalist, AI Kenya Challenge",
    title: "National Finalist at the Kenya AI Challenge, Nairobi",
    date: "August 2026",
    location: "Nairobi, Kenya",
    text: "Selected as a National Finalist at the Kenya AI Challenge finals in Nairobi. Presented our AI-powered farmer intelligence system alongside leading AI innovators and engineers from across Kenya.",
    story: "Competed at the prestigious Kenya AI Challenge Nairobi Finals, pitching DigiCow AI—an intelligent decision support system designed specifically for smallholder dairy farmers and youth extension agents. Out of hundreds of nationwide applicants, our team was selected to demonstrate how combining high-performance backend pipelines with domain-grounded AI can directly transform Kenya's agricultural economy.",
    roleAndImpact: "Lead backend engineer and knowledge graph architect. Integrated Neo4j with GraphRAG pipelines to completely eliminate generative hallucinations, grounding all livestock disease and agronomy advisories in certified KALRO and ILRI peer-reviewed manuals.",
    achievements: [
      "Selected as National Finalist at the Nairobi Finals amongst top Kenyan innovators",
      "Engineered sub-second bilingual retrieval pipelines (English & Swahili)",
      "Pitched live before panel of agricultural scientists, venture leaders, and government stakeholders",
    ],
    tech: ["Python", "FastAPI", "Neo4j Cypher", "GraphRAG", "Featherless AI"],
    tags: ["Nairobi, Kenya", "Kenya AI Challenge", "National Finalist"],
  },
  {
    id: "kijanispace-awards",
    category: ["awards"],
    image: "/assets/kijanispace-awards.jpg",
    badge: "Medalist, climate-smart agritech",
    title: "KijaniSpace Copernicus Hackathon medalist",
    date: "October 2025",
    location: "Kisumu, Kenya",
    text: "Honored with medals for engineering Copernicus Earth observation satellite pipelines that deliver soil moisture and localized climate advisories to smallholder farmers.",
    story: "Awarded medals at the KijaniSpace Climate-Smart Agritech Hackathon for creating Nemo, an Earth Observation intelligence system. We tackled localized drought vulnerabilities by processing multi-spectral Sentinel satellite data to forecast soil moisture deficits for cooperative farming clusters in Western Kenya.",
    roleAndImpact: "Designed satellite telemetry ingest pipelines and telemetry aggregation APIs, enabling remote farm field monitoring without expensive ground-sensor deployments.",
    achievements: [
      "Awarded hackathon medal for technical innovation and climate impact",
      "Synthesized satellite indices with localized farmer crop calendars",
      "Delivered SMS-based alert protocols for smallholder resilience",
    ],
    tech: ["Copernicus Sentinel Data", "Python", "Spatial Telemetry", "FastAPI"],
    tags: ["Copernicus EO", "Climate Tech", "Kisumu"],
  },
  {
    id: "zone01-sprints",
    category: ["sprints"],
    image: "/assets/zone01-coding.jpg",
    badge: "Zone01 Kisumu, systems sprint",
    title: "Deep-focus systems and concurrency sprints",
    date: "June 2026 – Present",
    location: "Zone01 Kisumu",
    text: "Building memory-safe concurrent Go pipelines, ASCII graphics engines, and microservices during hands-on development sprints at Zone01 Kisumu.",
    story: "Immersed in full-time peer-learning software engineering apprenticeship at Zone01 Kisumu (part of the global 01Edu network). Sprints are rigorously focused on first-principles engineering: building high-throughput systems in Go without relying on external libraries or third-party frameworks.",
    roleAndImpact: "Architecting concurrent worker pools, thread-safe communication channels, recursive parsers, and custom memory management structures. Mastering the mechanics of how operating systems schedule routines and allocate heap memory.",
    achievements: [
      "Built production-ready concurrent pipelines from scratch",
      "Completed 35+ core algorithmic benchmarks and systems evaluations",
      "Championed zero-dependency, memory-safe backend architectures",
    ],
    tech: ["Go", "Goroutines", "Channels", "Mutex Synchronization", "Linux"],
    tags: ["Go", "Worker Pools", "Peer Learning"],
  },
  {
    id: "lakehub-biochar",
    category: ["talks"],
    image: "/assets/lakehub-biochar-team.jpg",
    badge: "LakeHub Kisumu, Demo Day",
    title: "Durable biochar carbon removal team pitch",
    date: "July 2026",
    location: "LakeHub, Kisumu",
    text: "Standing with my co-builders presenting our SME and smallholder carbon credit verification platform to venture mentors, tech leaders, and community partners at LakeHub.",
    story: "Presented our climate-tech initiative at LakeHub Demo Day. We built a digital verification workflow enabling smallholder farmers and agricultural processors in Western Kenya to verify durable biochar carbon sequestration milestones, opening up verified voluntary carbon credits for rural communities.",
    roleAndImpact: "Developed audit logging mechanisms and secure verification endpoints to validate batch production milestones, ensuring complete traceability from biomass pyrolization to soil incorporation.",
    achievements: [
      "Presented to venture mentors and regional climate tech leaders",
      "Validated immutable carbon credit verification ledger",
      "Fostered partnerships with regional farmer cooperative networks",
    ],
    tech: ["Python", "Flask", "PostgreSQL", "Cryptographic Verification"],
    tags: ["LakeHub", "Carbon Removal", "SME Tech"],
  },
  {
    id: "nemo-pitch",
    category: ["talks"],
    image: "/assets/zone01-pitch.jpg",
    badge: "KijaniSpace Hackathon, pitch and demo",
    title: "Presenting Nemo, our KijaniSpace hackathon solution",
    date: "October 2025",
    location: "Kisumu, Kenya",
    text: "Pitching Nemo, our climate-smart agritech platform, at the KijaniSpace hackathon. Demonstrating Earth observation pipelines, soil moisture modeling, and farmer decision support live on stage.",
    story: "Delivered a live stage demonstration of Nemo to a panel of satellite scientists, agronomists, and hackathon judges. Walked through the complete user journey: from raw Copernicus Sentinel-2 satellite data ingestion to real-time risk scoring and SMS delivery to farmers.",
    roleAndImpact: "Demonstrated real-time query performance and explained the algorithmic pipeline behind the moisture stress index live on stage during technical Q&A.",
    achievements: [
      "Delivered live architecture presentation under tight time constraints",
      "Addressed judge technical inquiries on API latency and edge connectivity",
      "Celebrated with medals alongside co-builders",
    ],
    tech: ["Copernicus API", "Python", "FastAPI", "Satellite Imagery"],
    tags: ["KijaniSpace", "Nemo", "Agritech Demo"],
  },
  {
    id: "zone01-peer-review",
    category: ["sprints"],
    image: "/assets/zone01-collaboration.jpg",
    badge: "01 Edu, peer review",
    title: "Collaborative code reviews and pair programming",
    date: "2026",
    location: "Zone01 Kisumu",
    text: "Practicing active peer evaluation, breaking down algorithmic edge cases, and pair programming to keep codebases clean, maintainable, and bug-free.",
    story: "The Zone01 pedagogy relies on rigorous peer code reviews and collaborative pair programming. In this culture, code is only complete when verified by peers against comprehensive unit tests, memory leak checks, and defensive programming standards.",
    roleAndImpact: "Regularly conduct deep-dive code reviews, review pull requests, identify race conditions in concurrent Go routines, and mentor fellow apprentices through algorithmic bottlenecks.",
    achievements: [
      "Over 100+ peer code audits completed with constructive technical feedback",
      "Zero-defect standards on concurrent pipeline deliverables",
      "Fostered deep collaborative problem-solving culture",
    ],
    tech: ["Git", "GitHub", "Go Testing", "Benchmarking", "01Edu System"],
    tags: ["Pair Programming", "Code Review", "01 Edu"],
  },
  {
    id: "fireside-talk",
    category: ["talks"],
    image: "/assets/fireside-interview.jpg",
    badge: "Interview, AI and software engineering",
    title: "Interview: AI and software engineering",
    date: "September 2026",
    location: "Kisumu, Kenya",
    text: "Sharing perspectives on bridging artificial intelligence with core software engineering principles, concurrency, and domain-grounded solutions.",
    story: "Participated in an in-depth fireside conversation on the evolution of software engineering in the era of artificial intelligence. Discussed how fundamental engineering principles—like type safety, concurrency primitives, and deterministic databases—are more crucial than ever when deploying non-deterministic LLMs.",
    roleAndImpact: "Advocated for GraphRAG architectures and strict API contracts to ground AI in verifiable reality rather than relying on ungrounded generative predictions.",
    achievements: [
      "Shared technical insights on systems thinking and AI grounding",
      "Discussed challenges faced by smallholder farmers and tech solutions",
      "Encouraged aspiring women engineers in systems and backend engineering",
    ],
    tech: ["GraphRAG", "Knowledge Graphs", "Systems Architecture"],
    tags: ["AI and Engineering", "Interview", "Tech Talk"],
  },
];

export const momentFilters = [
  { key: "all", label: "All moments" },
  { key: "awards", label: "Hackathons and finals" },
  { key: "talks", label: "Stage talks and pitches" },
  { key: "sprints", label: "Systems coding sprints" },
];

export const skills = [
  {
    icon: "zap",
    title: "Backend and systems",
    chips: ["Go", "Python", "Concurrency and goroutines", "FastAPI", "Flask", "RESTful APIs", "Idempotent webhooks", "Gunicorn"],
    featured: ["Go", "Python"],
  },
  {
    icon: "brain",
    title: "Applied AI and GraphRAG",
    chips: ["Neo4j (Cypher)", "GraphRAG pipelines", "Featherless AI", "LLM grounding", "Scikit-learn", "Predictive modeling", "NumPy and Pandas"],
    featured: ["Neo4j (Cypher)", "GraphRAG pipelines"],
  },
  {
    icon: "database",
    title: "Databases and storage",
    chips: ["PostgreSQL", "Neo4j graph DB", "SQLite", "SQLAlchemy ORM", "Alembic migrations", "Schema modeling"],
    featured: ["PostgreSQL", "Neo4j graph DB"],
  },
  {
    icon: "tool",
    title: "DevOps, QA, and tooling",
    chips: ["Docker", "Git and GitHub", "Linux / Bash", "Paystack and M-Pesa", "Manual and API QA", "Defect lifecycle"],
    featured: ["Docker", "Git and GitHub"],
  },
];

export const openSourceProjects = [
  {
    name: "js-lings",
    title: "js-lings: Gamified JavaScript Learning Engine",
    description: "An interactive, gamified JavaScript practice environment inspired by Rustlings. Runs 100% locally and integrates seamlessly into VS Code for rapid developer feedback and algorithmic test-driven learning.",
    repoUrl: "https://github.com/Moraa021/js-lings",
    language: "JavaScript / Node",
    stars: 1,
    forks: 0,
    tags: ["Developer Tooling", "CLI", "VS Code", "Learning Engine"],
    featured: true,
  },
  {
    name: "digicow-ai-farmer-intelligence",
    title: "DigiCow AI: Farmer Intelligence System",
    description: "Open-source farmer decision support system powered by Neo4j Knowledge Graphs and GraphRAG retrieval pipelines. Delivers localized, zero-hallucination agricultural advisories for youth extension agents.",
    repoUrl: "https://github.com/Moraa021/digicow-ai-farmer-intelligence",
    language: "TypeScript / Python",
    stars: 1,
    forks: 0,
    tags: ["GraphRAG", "Neo4j", "FastAPI", "National Finalist"],
    featured: true,
  },
  {
    name: "PamojaBuild",
    title: "PamojaBuild: Concurrent Go Build & Task Pipeline",
    description: "A first-principles concurrent task runner and build engine written in Go. Leverages goroutine worker pools, channel multiplexing, and memory profiling with zero third-party runtime dependencies.",
    repoUrl: "https://github.com/Moraa021/pamojabuild1",
    language: "Go",
    stars: 1,
    forks: 0,
    tags: ["Go", "Concurrency", "Worker Pools", "Systems"],
    featured: true,
  },
  {
    name: "lightning-webstore",
    title: "Bitcoin Lightning Webstore",
    description: "Flask web application integrating native Bitcoin Lightning Network payments via LND REST API, automated invoice polling, and Polar local testnet auto-detection.",
    repoUrl: "https://github.com/Moraa021/lightning-webstore",
    language: "Python / Flask",
    stars: 0,
    forks: 0,
    tags: ["Bitcoin", "Lightning Network", "LND", "Fintech"],
  },
  {
    name: "Sift",
    title: "Sift: Feedback Categorization Pipeline",
    description: "Automated customer feedback intelligence tool using natural language processing to categorize support tickets, detect user sentiment, and prioritize critical bug reports.",
    repoUrl: "https://github.com/Moraa021/Sift",
    language: "Python",
    stars: 0,
    forks: 0,
    tags: ["Machine Learning", "NLP", "Python", "Data Processing"],
  },
  {
    name: "LedgerMate",
    title: "LedgerMate Open Financial Engine",
    description: "Lightweight SME accounting backend featuring cryptographic M-Pesa / Paystack webhook verification, automated transaction reconciliation, and financial report generation.",
    repoUrl: "https://github.com/Moraa021/LedgerMate",
    language: "Python / HTML",
    stars: 0,
    forks: 0,
    tags: ["Accounting", "Paystack", "M-Pesa", "Flask"],
  },
  {
    name: "kisumu-lang",
    title: "kisumu-lang: Localized Language Interpreter",
    description: "An experimental localized programming language exploring lexical analysis, recursive descent parsing, and abstract syntax tree (AST) interpretation.",
    repoUrl: "https://github.com/Moraa021/kisumu-lang",
    language: "Go / Interpreter",
    stars: 0,
    forks: 0,
    tags: ["Compilers", "AST", "Parsers", "Languages"],
  },
  {
    name: "open-source-contributions",
    title: "Open Source Code Contributions",
    description: "Curated collection of upstream contributions, bug fixes, beginner onboarding guides, and documentation improvements across open-source developer ecosystems.",
    repoUrl: "https://github.com/Moraa021/open-source-code-contributions",
    language: "Markdown / Shell",
    stars: 0,
    forks: 0,
    tags: ["Community", "Documentation", "Git", "Peer Learning"],
  },
];

export const hobbies = [
  {
    image: "/assets/oss-pr-merged.png",
    title: "Open-source contribution",
    text: "Contributing to and maintaining public repositories, reviewing pull requests, and building small tools in the open.",
  },
  {
    image: "/assets/laptop-work.jpg",
    title: "Technical writing",
    text: "Writing on dev.to about systems, concurrency, and applied AI, turning what I learn on the job into shareable notes.",
  },
  {
    image: "/assets/soccer-hobby.jpg",
    title: "Playing soccer",
    text: "Weekly matches with friends. It is where I reset, and honestly where some of my best debugging ideas show up.",
  },
];

export const articles = [
  {
    tag: "AI & GraphRAG",
    title: "From Shredded Papers to the Grand Map Room: Why Knowledge Graphs are Revolutionizing RAG",
    excerpt: "Imagine an intelligence agency whose sole mission is to answer complex questions about global systems. A deep dive into how knowledge graphs eliminate LLM hallucinations by connecting structured concepts.",
    url: "https://dev.to/memoraa/from-shredded-papers-to-the-grand-map-room-why-knowledge-graphs-are-revolutionizing-rag-22c3",
    date: "Sep 7",
    readingTime: "3 min read",
    tags: ["AI", "RAG", "Architecture", "LLM"],
    image: "https://media2.dev.to/dynamic/image/width=1200,height=627,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.us-east-2.amazonaws.com%2Fuploads%2Farticles%2F8tim2unhcmzrwrxh4sco.png",
  },
  {
    tag: "QA & Reliability",
    title: "The QA Mindset: What 3 Weeks of Breaking Code Taught Me About Building Better Software",
    excerpt: "When I first started writing software, my primary measure of success was making it work. Here is what 3 weeks of intensive QA and breaking systems taught me about building defensible software.",
    url: "https://dev.to/memoraa/the-qa-mindset-what-3-weeks-of-breaking-code-taught-me-about-building-better-software-48dn",
    date: "Aug 27",
    readingTime: "4 min read",
    tags: ["QA", "Testing", "WebDev", "Software Engineering"],
    image: "https://media2.dev.to/dynamic/image/width=1200,height=627,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.us-east-2.amazonaws.com%2Fuploads%2Farticles%2F1ibgobvl6h6bma8bbvjo.png",
  },
  {
    tag: "Git & Systems",
    title: "Git Graph Explained: Visualizing Merge, Rebase, and Cherry-Pick",
    excerpt: "Git is the ultimate tool for developers, yet branching strategies still confuse many. Visualizing the commit graph makes complex merges, rebases, and cherry-picks intuitive and manageable.",
    url: "https://dev.to/memoraa/git-graph-explained-visualizing-merge-rebase-and-cherry-pick-23f0",
    date: "Aug 3",
    readingTime: "3 min read",
    tags: ["Git", "Version Control", "Tutorial", "Engineering"],
    image: "https://media2.dev.to/dynamic/image/width=1200,height=627,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.us-east-2.amazonaws.com%2Fuploads%2Farticles%2Fk4k0v5g4adl1kgmk5c2q.png",
  },
  {
    tag: "Security & DevOps",
    title: "How I Pushed My .env and Database to GitHub (And How to Fix It)",
    excerpt: "We have all been there. You are excited about a project, your code finally works, and you accidentally leak secrets. Here is a definitive, panic-free guide to scrubbing Git history.",
    url: "https://dev.to/memoraa/how-i-pushed-my-env-and-database-to-github-and-how-to-fix-it-1g58",
    date: "Jul 30",
    readingTime: "3 min read",
    tags: ["Security", "Git", "GitHub", "DevOps"],
    image: "https://media2.dev.to/dynamic/image/width=1200,height=627,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.us-east-2.amazonaws.com%2Fuploads%2Farticles%2Fgcrgnr7sn6u3tgwhun5g.png",
  },
  {
    tag: "Bitcoin & Blockchain",
    title: "Navigating Bitcoin Core: A Developer Introduction to Scripting the Blockchain",
    excerpt: "Most developers interact with blockchain at high levels. Let's dig into Bitcoin Core primitives, UTXO validation, and low-level script execution using Python.",
    url: "https://dev.to/memoraa/navigating-bitcoin-core-a-developer-introduction-to-scripting-the-blockchain-5f92",
    date: "Jun 8",
    readingTime: "4 min read",
    tags: ["Bitcoin", "Python", "Blockchain", "Scripting"],
    image: "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/3otvb2z646ytpt1hl2rv.jpg",
  },
  {
    tag: "Machine Learning",
    title: "Building ML Pipelines with Python: From Data to Insights",
    excerpt: "In machine learning, training a model on a clean dataset is only a fraction of the challenge. Here is how to construct repeatable data transformations and automated inference pipelines.",
    url: "https://dev.to/memoraa/building-ml-pipelines-with-python-from-data-to-insights-3bkc",
    date: "Jun 7",
    readingTime: "4 min read",
    tags: ["Python", "Machine Learning", "Data Science"],
    image: "https://media2.dev.to/dynamic/image/width=1200,height=627,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fqypnbpel2cz81whuo3sx.png",
  },
  {
    tag: "Go Systems",
    title: "Getting Started with Go: A Beginner's Journey",
    excerpt: "If you told me a few months ago that I would be obsessed with pointers, memory allocation, and channels, I wouldn't believe it. An honest, practical guide to starting Go systems programming.",
    url: "https://dev.to/memoraa/getting-started-with-go-a-beginners-journey-1491",
    date: "Jun 7",
    readingTime: "3 min read",
    tags: ["Go", "Systems", "Backend", "Beginner Guide"],
    image: "https://media2.dev.to/dynamic/image/width=1200,height=627,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fa2gro0rb0m4y45p9ljb0.png",
  },
];
